# Devin/config/os_specific/android.yaml
# Purpose: Android-specific configuration settings, focusing on ADB commands and paths.

# --- ADB Tool Configuration ---
adb_tool:
  # Path to the ADB executable on the HOST system running Devin.
  # Set to null to assume 'adb' is in the system's PATH.
  host_executable_path: null
  # Default timeout in seconds for ADB commands (can be overridden per command)
  default_command_timeout_sec: 15

# --- Common Android Filesystem Paths ---
# Note: Access depends on ADB permissions (shell user) and device state (rooted?).
paths:
  # Standard user-accessible storage directory
  sdcard_root: "/sdcard"
  # Common location for downloads
  downloads_dir: "/sdcard/Download"
  # Internal storage directory often used for temp files by apps
  data_local_tmp: "/data/local/tmp" # Usually writable by shell user via ADB
  # Location where screenshots are typically saved by 'screencap'
  default_screenshot_path_device: "/sdcard/screenshot.png"
  # Common location for system binaries
  system_bin: "/system/bin"

# --- Standard ADB Command Structures ---
# Provides templates for common ADB commands Devin might construct.
# Placeholders like {placeholder_name} would be replaced by the control logic.
adb_commands:
  # Base command prefixes
  shell_base: "shell"
  specify_device_flag: "-s {device_serial}" # Optional flag added if multiple devices or specific serial needed

  # Package Management
  list_packages: "shell pm list packages -f {filter_flags}" # e.g., -3 for third-party, -s for system
  get_apk_path: "shell pm path {package_name}"
  install_apk_flags: "install -r -g" # Flags: -r=reinstall, -g=grant permissions
  uninstall_package: "uninstall {package_name}"

  # Device Interaction
  get_property: "shell getprop {property_name}" # e.g., ro.build.version.sdk
  get_displays: "shell dumpsys display" # Get display info, needs parsing
  screenshot_cmd: "shell screencap -p" # Saves to stdout as PNG
  screenshot_to_file_cmd: "shell screencap -p {device_path}" # Saves to device path
  screenrecord_cmd: "shell screenrecord {options} {device_path}" # e.g., options="--time-limit 10"
  input_text_cmd: "shell input text '{text_to_input}'" # Text needs escaping for shell
  input_keyevent_cmd: "shell input keyevent {key_code_or_name}" # Use keycodes from below
  input_tap_cmd: "shell input tap {x_coord} {y_coord}"
  input_swipe_cmd: "shell input swipe {x1} {y1} {x2} {y2} {duration_ms}"
  start_activity_cmd: "shell am start -n {component_name}" # e.g., com.android.settings/.Settings
  start_activity_with_action_cmd: "shell am start -a {action_name} -d {data_uri}" # e.g., android.intent.action.VIEW
  force_stop_package: "shell am force-stop {package_name}"
  clear_package_data: "shell pm clear {package_name}" # Requires permissions

  # File Transfer
  pull_file: "pull {device_path} {host_path}"
  push_file: "push {host_path} {device_path}"

  # Connectivity
  get_wifi_status: "shell dumpsys wifi | grep -E 'mWifiInfo'" # Needs parsing
  get_ip_addr: "shell ip addr show wlan0 | grep 'inet ' | cut -d ' ' -f 6 | cut -d / -f 1" # Example for wlan0

# --- Android Keycode Mappings ---
# Common key event names mapped to their Android integer keycodes.
# See Android KeyEvent documentation for a full list.
keycodes:
  UNKNOWN: 0
  SOFT_LEFT: 1
  SOFT_RIGHT: 2
  HOME: 3
  BACK: 4
  CALL: 5
  ENDCALL: 6
  DPAD_UP: 19
  DPAD_DOWN: 20
  DPAD_LEFT: 21
  DPAD_RIGHT: 22
  DPAD_CENTER: 23
  VOLUME_UP: 24
  VOLUME_DOWN: 25
  POWER: 26
  CAMERA: 27
  CLEAR: 28
  A: 29
  B: 30
  # ... (add letters A-Z = 29-54)
  Z: 54
  COMMA: 55
  PERIOD: 56
  ALT_LEFT: 57
  ALT_RIGHT: 58
  SHIFT_LEFT: 59
  SHIFT_RIGHT: 60
  TAB: 61
  SPACE: 62
  SYM: 63 # Symbol key
  EXPLORER: 64
  ENVELOPE: 65 # Email key
  ENTER: 66
  DEL: 67 # Backspace
  GRAVE: 68 # `
  MINUS: 69
  EQUALS: 70
  LEFT_BRACKET: 71
  RIGHT_BRACKET: 72
  BACKSLASH: 73
  SEMICOLON: 74
  APOSTROPHE: 75
  SLASH: 76
  AT: 77 # @
  NUM: 78
  HEADSETHOOK: 79
  FOCUS: 80
  PLUS: 81
  MENU: 82
  NOTIFICATION: 83
  SEARCH: 84
  # Media keys
  MEDIA_PLAY_PAUSE: 85
  MEDIA_STOP: 86
  MEDIA_NEXT: 87
  MEDIA_PREVIOUS: 88
  MEDIA_REWIND: 89
  MEDIA_FAST_FORWARD: 90
  MUTE: 91
  # Number keys 0-9 = 7-16
  NUM_0: 7
  NUM_1: 8
  NUM_2: 9
  NUM_3: 10
  NUM_4: 11
  NUM_5: 12
  NUM_6: 13
  NUM_7: 14
  NUM_8: 15
  NUM_9: 16
  # Add other useful keycodes

# --- Android Settings Database Commands ---
# Commands for interacting with the Android settings provider (requires permissions).
device_settings:
  get_global_setting: "shell settings get global {setting_name}"
  put_global_setting: "shell settings put global {setting_name} {value}"
  get_system_setting: "shell settings get system {setting_name}"
  put_system_setting: "shell settings put system {setting_name} {value}"
  get_secure_setting: "shell settings get secure {setting_name}"
  put_secure_setting: "shell settings put secure {setting_name} {value}" # Usually needs root or special permission

# Add other Android-specific settings as needed...
